---
version: '2'
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms.connectors.default_listen_address=0.0.0.0
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_AUTH=neo4j/test
    volumes:
      - $HOME/Public/docker/neo4j/data:/data
      - $HOME/Public/docker/neo4j/logs:/logs
      - $HOME/Public/docker/neo4j/import:/var/lib/neo4j/import
      - $HOME/Public/docker/neo4j/plugins:/plugins
volumes:
  datavolume: